# Generated by Django 5.0.3 on 2024-03-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favlink",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
