# Generated by Django 5.0.3 on 2024-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_alter_favlink_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="favlink",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
