# Generated by Django 5.0.3 on 2024-03-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0003_favlink_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favlink",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="links",
                to="links.category",
            ),
        ),
        migrations.AlterField(
            model_name="favlink",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="favlink",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="links", to="links.tag"
            ),
        ),
    ]
