# Generated by Django 5.0.3 on 2024-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0004_alter_favlink_category_alter_favlink_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favlink",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="links", to="links.tag"
            ),
        ),
    ]
