# Generated by Django 5.0.3 on 2024-03-19 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0006_alter_category_name_alter_favlink_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favlink",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
