# Generated by Django 5.0.3 on 2024-03-19 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0008_favlink_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favlink",
            name="note",
        ),
    ]
